spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: never


dataLoaderMode: never  #always bo'lsa proekt run bo'lganda avtamat bazaga malumot qo'shadi(role, permission va h.k)

accessTokenLifeTime: 86400
refreshTokenLifeTime: 172800

tokenSecretKey: 9OhGa*6i6RiB5!~mg@w"fidFi1iuc~0A@D

